[package]
name = "ultimate_ttt"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["ai"]
resolver = "2"

[dependencies]
bincode = "2.0.1"
serde = { version = "1.0.228", features = ["derive"] }
